### ISSUE TITLE
Unable to build with polymer

### ISSUE THREAD

**Issue by yelinaung** [gdg-x/hoverboard#110]
Hello,

I am getting `error:   Uncaught exception: Error: no writecb in Transform class` error while running `polymer build`. Here's the logs 

```
λ ~/work/misc/hoverboard/ master polymer build
info:    Building application...
info:    Generating build/unbundled...
info:    Generating build/bundled...
warn:    Unable to uglify file /home/yelinaung/work/misc/hoverboard/index.html_script_1.js
warn:    Unable to uglify file /home/yelinaung/work/misc/hoverboard/src/pages/blog-list.html_script_0.js
error:   Uncaught exception: Error: no writecb in Transform class
error:   Error: no writecb in Transform class
    at afterTransform (_stream_transform.js:71:33)
    at TransformState.afterTransform (_stream_transform.js:54:12)
    at Splitter._transform (/home/yelinaung/.nvm/versions/node/v6.3.0/lib/node_modules/polymer-cli/lib/build/html-project.js:132:17)
    at Splitter.Transform._read (_stream_transform.js:167:10)
    at Splitter.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at Splitter.Writable.write (_stream_writable.js:220:11)
    at DestroyableTransform.ondata (/home/yelinaung/.nvm/versions/node/v6.3.0/lib/node_modules/polymer-cli/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:531:20)
    at emitOne (events.js:96:13)
warn:    Unable to uglify file /home/yelinaung/work/misc/hoverboard/bower_components/intl-messageformat/src/compiler.js
warn:    Unable to uglify file /home/yelinaung/work/misc/hoverboard/bower_components/intl-messageformat/src/core.js
warn:    Unable to uglify file /home/yelinaung/work/misc/hoverboard/bower_components/intl-messageformat/src/en.js
warn:    Unable to uglify file /home/yelinaung/work/misc/hoverboard/bower_components/intl-messageformat/src/es5.js
warn:    Unable to uglify file /home/yelinaung/work/misc/hoverboard/bower_components/intl-messageformat/src/main.js
warn:    Unable to uglify file /home/yelinaung/work/misc/hoverboard/bower_components/intl-messageformat/src/utils.js
warn:    Unable to uglify file /home/yelinaung/work/misc/hoverboard/bower_components/marked-element/demo/index.html_script_0.js
warn:    Unable to uglify file /home/yelinaung/work/misc/hoverboard/bower_components/marked-element/test/marked-element.html_script_0.js
warn:    Unable to uglify file /home/yelinaung/work/misc/hoverboard/bower_components/marked-element/test/marked-element.html_script_1.js
warn:    Unable to uglify file /home/yelinaung/work/misc/hoverboard/bower_components/marked-element/test/marked-element.html_script_2.js
warn:    Unable to uglify file /home/yelinaung/work/misc/hoverboard/bower_components/marked-element/test/marked-element.html_script_3.js
warn:    Unable to uglify file /home/yelinaung/work/misc/hoverboard/bower_components/marked-element/test/marked-element.html_script_4.js
warn:    Unable to uglify file /home/yelinaung/work/misc/hoverboard/bower_components/marked-element/test/marked-element.html_script_5.js
warn:    Unable to uglify file /home/yelinaung/work/misc/hoverboard/bower_components/web-component-tester/data/index.html_script_0.js
warn:    Unable to uglify file /home/yelinaung/work/misc/hoverboard/bower_components/web-component-tester/data/index.html_script_2.js
```

And when I deploy it to firebase, the website is broken with errors which can be found in console. The site can be found at https://devfest.gdgyangon.org. 

My `node --version` is `6.3.0`. npm version is `3.10.6`.

Please let me know if there are any other information I can provide. Thanks!

**Comment by ozasadnyy** [comment]
Hello @yelinaung , which version of Polymer CLI do you have?

**Comment by yelinaung** [comment]
Hello @ozasadnyy , the `polymer --version` is `0.12.0`

**Comment by ozasadnyy** [comment]
Have you changed any styles?

**Comment by yelinaung** [comment]
I think I have made a bunch of changes. That could be the case. I will check it out and get back to you.  Thanks for the help!

**Comment by ozasadnyy** [comment]
@yelinaung  check for missed semicolons at the end of lines in styles and scripts.

**Comment by yelinaung** [comment]
@ozasadnyy I have found the issue in one of the data file. Thanks a lot for the help. I will close the issue.
