### ISSUE TITLE
Build is failing and I'm unable to see the website using Firebase Hosting

### ISSUE THREAD

**Issue by juarezpaf** [gdg-x/hoverboard#122]
I changed all files that I needed and I don't have any error running it locally, but when I try to build, it just fails and also after `firebase deploy` I got no luck https://devfestne2016.firebaseapp.com
```
➜  hoverboard git:(master) ✗ polymer build
info:    Building application...
warn:    Unable to optimize .js file /Users/juarezfilho/Playground/devfest/hoverboard/index.html_script_2.js
{ err:
   { message: 'SyntaxError: Unexpected token: punc (:)',
     filename: 0,
     line: 3,
     col: 16,
     pos: 23,
     stack: 'Error\n    at new JS_Parse_Error (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1545:18)\n    at js_error (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1553:11)\n    at croak (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2092:9)\n    at token_error (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2100:9)\n    at unexpected (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2106:9)\n    at semicolon (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2126:56)\n    at simple_statement (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2317:73)\n    at eval (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2167:47)\n    at eval (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2139:24)\n    at block_ (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2432:20)' } }
info:    Generating build/unbundled...
info:    Generating build/bundled...
```

**Comment by MrCsabaToth** [comment]
Possibly duplicate of #86 
@juarezpaf make sure you use Polymer 0.12
Build won't work with newer versions.

**Comment by juarezpaf** [comment]
Thanks @MrCsabaToth 👍
