### ISSUE TITLE
developer branch build problem

### ISSUE THREAD

**Issue by MrCsabaToth** [gdg-x/hoverboard#221]
I'm running now on Ubuntu 16.10 Yakkety Yak. First I tried with the Ubuntu official nodejs 0.4.9, but then I upgraded to the latest stable 7.4.0. I upgraded polymer-cli from 0.16 to 0.17 also. Reinstalled firebase-tools (probably doesn't matter).

gulp:
> [23:18:15] CLI version 3.9.1
> [23:18:15] Local version 4.0.0-alpha.2

What else can matter?

polymer build:
> info:    Preparing build...
info:    Building application...
info:    Generating build/unbundled...
info:    Generating build/bundled...
warn:    Unable to optimize .js file /home/csaba/GitRepos/WTM2017/src/hoverboard-app.html_script_0.js 
{ err: 
   { message: 'SyntaxError: Unexpected token name «pages», expected punc «:»',
     filename: 0,
     line: 41,
     col: 22,
     pos: 801,
     stack: 'Error\n    at new JS_Parse_Error (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1547:18)\n    at js_error (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1555:11)\n    at croak (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2094:9)\n    at token_error (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2102:9)\n    at expect_token (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2115:9)\n    at expect (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2118:36)\n    at eval (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2691:13)\n    at eval (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2141:24)\n    at expr_atom (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2621:35)\n    at maybe_unary (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2797:19)' } }
error:   Promise rejection: Error: Error parsing script in src/hoverboard-app.html at 193:25
SyntaxError: Unexpected token pages
    at Parser.instance.raise.instance.raiseRecoverable (/usr/local/lib/node_modules/polymer-cli/node_modules/espree/espree.js:408:19)
    at Parser.instance.unexpected (/usr/local/lib/node_modules/polymer-cli/node_modules/espree/espree.js:441:14)
    at Parser.pp.expect (/usr/local/lib/node_modules/polymer-cli/node_modules/acorn/dist/acorn.js:610:26)
    at Parser.instance.parseObj (/usr/local/lib/node_modules/polymer-cli/node_modules/espree/espree.js:331:22)
    at Parser.pp$3.parseExprAtom (/usr/local/lib/node_modules/polymer-cli/node_modules/acorn/dist/acorn.js:1969:17)
    at Parser.pp$3.parseExprSubscripts (/usr/local/lib/node_modules/polymer-cli/node_modules/acorn/dist/acorn.js:1854:19)
    at Parser.pp$3.parseMaybeUnary (/usr/local/lib/node_modules/polymer-cli/node_modules/acorn/dist/acorn.js:1831:17)
    at Parser.pp$3.parseExprOps (/usr/local/lib/node_modules/polymer-cli/node_modules/acorn/dist/acorn.js:1773:19)
    at Parser.pp$3.parseMaybeConditional (/usr/local/lib/node_modules/polymer-cli/node_modules/acorn/dist/acorn.js:1756:19)
    at Parser.pp$3.parseMaybeAssign (/usr/local/lib/node_modules/polymer-cli/node_modules/acorn/dist/acorn.js:1733:19)
error:   Error: Error parsing script in src/hoverboard-app.html at 193:25
SyntaxError: Unexpected token pages
    at Parser.instance.raise.instance.raiseRecoverable (/usr/local/lib/node_modules/polymer-cli/node_modules/espree/espree.js:408:19)
    at Parser.instance.unexpected (/usr/local/lib/node_modules/polymer-cli/node_modules/espree/espree.js:441:14)
    at Parser.pp.expect (/usr/local/lib/node_modules/polymer-cli/node_modules/acorn/dist/acorn.js:610:26)
    at Parser.instance.parseObj (/usr/local/lib/node_modules/polymer-cli/node_modules/espree/espree.js:331:22)
    at Parser.pp$3.parseExprAtom (/usr/local/lib/node_modules/polymer-cli/node_modules/acorn/dist/acorn.js:1969:17)
    at Parser.pp$3.parseExprSubscripts (/usr/local/lib/node_modules/polymer-cli/node_modules/acorn/dist/acorn.js:1854:19)
    at Parser.pp$3.parseMaybeUnary (/usr/local/lib/node_modules/polymer-cli/node_modules/acorn/dist/acorn.js:1831:17)
    at Parser.pp$3.parseExprOps (/usr/local/lib/node_modules/polymer-cli/node_modules/acorn/dist/acorn.js:1773:19)
    at Parser.pp$3.parseMaybeConditional (/usr/local/lib/node_modules/polymer-cli/node_modules/acorn/dist/acorn.js:1756:19)
    at Parser.pp$3.parseMaybeAssign (/usr/local/lib/node_modules/polymer-cli/node_modules/acorn/dist/acorn.js:1733:19)
    at Analyzer._processScript (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:331:36)
    at /usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:301:44
    at Array.forEach (native)
    at Analyzer._processScripts (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:300:21)
    at Analyzer._parseHTML (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:161:39)
    at Timeout._onTimeout (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:125:39)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)

**Comment by ozasadnyy** [comment]
@MrCsabaToth, thanks for using dev branch, you are playing with new features together :)
gulp task was fixed in #219. Please confirm if it works for you (now we generate only bundled or unbundled version)

**Comment by MrCsabaToth** [comment]
That's how I live dangerously :) #219 seems to be merged into develop 2 days ago, so I must have had it last night when I cloned.

**Comment by MrCsabaToth** [comment]
I narrowed down the cause to two lines:

1. https://github.com/gdg-x/hoverboard/blob/develop/src/hoverboard-app.html#L257 `value: {$ pages | dump | safe $}` 
2. https://github.com/gdg-x/hoverboard/blob/develop/src/elements/map-block.html#L209 `value: {$ location.images | dump | safe $}`

Somehow this `{$ ... $}` doesn't fly well in my toolchain right now. How can I cure this?

**Comment by MrCsabaToth** [comment]
Looks like substitution in general is crippled: https://wtm2017-146fd.firebaseio.com

**Comment by MrCsabaToth** [comment]
Sorry, correct URL https://wtm2017-146fd.firebaseapp.com/

**Comment by ozasadnyy** [comment]
@MrCsabaToth nunjucks should compile a template before polymer-build. Could you send information about your environment and output from the console?

**Comment by MrCsabaToth** [comment]
Oh, I didn't say `gulp` but I said `polymer build`...

**Comment by MrCsabaToth** [comment]
I guess the new `develop` branch won't do `polymer build` any more? I see that the firebase.json points to `./build` as the public directory. `firebase build` would still try to create the `bundled` and `unbundled` and that's why my firebase links dont' work any more.

As for gulp:

> csaba@titan:~/GitRepos/WTM2017$ gulp
[21:20:01] Using gulpfile ~/GitRepos/WTM2017/gulpfile.js
/usr/local/lib/node_modules/gulp/bin/gulp.js:129
    gulpInst.start.apply(gulpInst, toRun);
                  ^

TypeError: Cannot read property 'apply' of undefined
    at /usr/local/lib/node_modules/gulp/bin/gulp.js:129:19
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:607:11)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3
csaba@titan:~/GitRepos/WTM2017$ gulp -v
[21:20:37] CLI version 3.9.1
[21:20:37] Local version 4.0.0-alpha.2

**Comment by MrCsabaToth** [comment]
Ok, solved that gulp error above with https://github.com/gulpjs/gulp-cli/issues/9#issuecomment-259888997

And the build process is now `gulp` instead of `polymer build`

**Comment by MrCsabaToth** [comment]
Actually, simply `sudo npm install -g gulp-cli` is enough, that will install 1.2.2

**Comment by MrCsabaToth** [comment]
And now we should `gulp serve` instead of `polymer serve` also.

**Comment by MrCsabaToth** [comment]
https://stackoverflow.com/questions/40220183/error-in-gulp-js

**Comment by MrCsabaToth** [comment]
Solved

**Comment by ozasadnyy** [comment]
I have to update the documentation :)

**Comment by MrCsabaToth** [comment]
Created a PR. I had to say just `gulp` instead of `gulp build`. Should the root README updated?

**Comment by ozasadnyy** [comment]
It would be nice. I have made mistakes with serve url and build command (don't need 'build'). Could you send another PR?
