### ISSUE TITLE
Unexpected token 

### ISSUE THREAD

**Issue by pamuditha** [gdg-x/hoverboard#320]
/home/imalka/Documents/Devfest/hoverboard/gulpfile.js:34
  fragments: polymerJson.fragments.reduce((res, el) => [...res, prependPath(config.tempDirectory, el)], []),
                                                        ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at execute (/home/imalka/Documents/Devfest/hoverboard/node_modules/gulp-cli/lib/versioned/^4.0.0-alpha.2/index.js:37:18)
    at Liftoff.handleArguments (/home/imalka/Documents/Devfest/hoverboard/node_modules/gulp-cli/index.js:173:63)
    at Liftoff.<anonymous> (/home/imalka/Documents/Devfest/hoverboard/node_modules/liftoff/index.js:198:16)

npm ERR! Linux 4.4.0-53-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "serve"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! hoverboard@1.2.0 serve: `gulp serve`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hoverboard@1.2.0 serve script 'gulp serve'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the hoverboard package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp serve
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs hoverboard
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls hoverboard
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/imalka/Documents/Devfest/hoverboard/npm-debug.log

**Comment by obilodeau** [comment]
I guess the answer is to update node?
