### ISSUE TITLE
issue while executing 'npm run build'

### ISSUE THREAD

**Issue by smaillns** [gdg-x/hoverboard#356]
I have already tried to deploy, but this time i find unexpected problem while _building the project !
where is the problem exactly ?!!

>[14:56:56] 'default' errored after 1.75 min
[14:56:56] TypeError: file.isSymbolic is not a function
    at DestroyableTransform.normalize [as _transform] (C:\Users\******\Desktop\hoverboard\node_modules\vinyl-fs\lib\dest\prepare.js:31:15) at DestroyableTransform.Transform._read (C:\Users\*****\Desktop\hoverboard\node_modules\readable-stream\lib\_stream_transform.js:182:10)   at DestroyableTransform.Transform._write (C:\Users\*******\Desktop\hoverboard\node_modules\readable-stream\lib\_stream_transform.js:170:83)    
 at doWrite ( C : \ U sers \*******\ Desktop\hoverboard\node_modules\ readablestream\lib\_stream_writable.js:406:64)   at writeOrBuffer (C:\Users\********\Desktop\hoverboard\ node_modules\readablestream\lib\_stream_writable.js:395:5)atDestroyableTransform.Writable.write(C:\Users\*****\Desktop\hoverboard\node_modules\readable-stream\lib\_stre
>
> npm ERR! code ELIFECYCLE
 npm ERR! errno 1
 npm ERR! hoverboard@1.2.0 build: `gulp`
 npm ERR! Exit status 1
 npm ERR!
 npm ERR! Failed at the hoverboard@1.2.0 build script.
 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

> npm ERR! A complete log of this run can be found in:
 npm ERR!     C:\Users\*********\AppData\Roaming\npm-cache\_logs\2017-12-24T13_56_56_866Z-
 debug.log

**Comment by smaillns** [comment]
@ozasadnyy may you help me ?

**Comment by ozasadnyy** [comment]
it's gulp related issue. Please refer to their repository. They already have a created issue: https://github.com/gulpjs/gulp/issues/2065

**Comment by smaillns** [comment]
why did you close the issue?!! I already saw the last link and i steal have the same issue

**Comment by ozasadnyy** [comment]
Because this problem is not related to the source code of this project and it's more convenient to follow the existing issue on the project that produces it. Have you tried to downgrade gulp and try to build with that version?

**Comment by smaillns** [comment]
I tried to do that .. I'm sure and didn't work but this time it works  ! yes
(so the problem was in gulp version ,  v 4.0.0-alpha.3 ==> 4.0.0-alpha.2)
thank you so much @ozasadnyy
