### ISSUE TITLE
Deploy issues on v2

### ISSUE THREAD

**Issue by Nuruddinjr** [gdg-x/hoverboard#438]
After installing everything on npm, now I have problems with deploying
Here are the logs, my firebase json has 
```
"hosting": {
    "public": "build/bundled",
```

`$ firebase deploy`

```
=== Deploying to 'project-4008939318649506790'...

i  deploying database, storage, functions, hosting
Running command: npm --prefix $RESOURCE_DIR run build

> hoverboard-functions@ prebuild /Users/nuruddin/Desktop/io-website/functions
> rimraf lib


> hoverboard-functions@ build /Users/nuruddin/Desktop/io-website/functions
> babel src --out-dir dist --source-maps

🎉  Successfully compiled 7 files with Babel.

> hoverboard-functions@ postbuild /Users/nuruddin/Desktop/io-website/functions
> cp ../build/index.html dist/

✔  functions: Finished running predeploy script.
i  database: checking rules syntax...
✔  database: rules syntax for database project-4008939318649506790 is valid
i  storage: checking storage.rules for compilation errors...
✔  storage: rules file storage.rules compiled successfully
i  functions: ensuring necessary APIs are enabled...
✔  functions: all necessary APIs are enabled

Error: Specified public directory does not exist, can't deploy hosting
```

If I run `yarn deploy`, I get the following
```
yarn deploy
yarn run v1.6.0
$ cd ./functions && npm i
up to date in 4.386s
$ gulp deploy
File path config/development.json selected as config...
[10:35:52] Using gulpfile ~/Desktop/io-website/gulpfile.js
[10:35:52] Starting 'deploy'...
[10:36:09] 'deploy' errored after 18 s
[10:36:09] Error: Command `firebase use project-4008939318649506790 && firebase deploy` exited with code 1
    at ChildProcess.handleSubShellExit (/Users/nuruddin/Desktop/io-website/node_modules/gulp-run/command.js:166:13)
    at Object.onceWrapper (events.js:275:13)
    at ChildProcess.emit (events.js:182:13)
    at ChildProcess.EventEmitter.emit (domain.js:460:23)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:225:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by ozasadnyy** [comment]
For now please run 'yarn build' and then 'firebase deploy'. I will take a look to this issue later

**Comment by Nuruddinjr** [comment]
@ozasadnyy https://github.com/gdg-x/hoverboard/pull/314 this solves the problem, I entered `build/bundled/` when I was running `firebase init` but, it should be `build/`

**Comment by ozasadnyy** [comment]
Docs were updated.
Note, they are not updated yet as we waiting for final release.

**Comment by Nuruddinjr** [comment]
Got it thanks
