### ISSUE TITLE
gulp init fails when repo was downloaded

### ISSUE THREAD

**Issue by zasadnyy** [gdg-x/hoverboard#50]
Download repo as a zip, try to run `gulp init`, the error will be returned:

```
~/Desktop/tmp/devfest-nl/hoverboard-master ⮀  ⮀  ⮀ gulp init
fatal: Not a git repository (or any of the parent directories): .git
child_process.js:1389
    throw err;
          ^
Error: Command failed: git describe --tags
fatal: Not a git repository (or any of the parent directories): .git

    at checkExecSyncError (child_process.js:1346:13)
    at execSync (child_process.js:1386:13)
    at Object.<anonymous> (/Users/vitalik/Desktop/tmp/devfest-nl/hoverboard-master/config.js:2:19)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/vitalik/Desktop/tmp/devfest-nl/hoverboard-master/gulpfile.js:26:14)
```

**Comment by ozasadnyy** [comment]
Fixed in #51
