### ISSUE TITLE
develop: app fails to render anything but blank toolbar and sidenav

### ISSUE THREAD

**Issue by Splaktar** [gdg-x/hoverboard#86]
Using the current `develop` with no modifications, I'm seeing the following:

`polymer build`:
```
info:    Building application...
warn:    Unable to optimize .js file /Users/splaktar/Git/gdgspacecoast/hoverboard/index.html_script_1.js 
{ err: 
   { message: 'SyntaxError: Unexpected token: punc (:)',
     filename: 0,
     line: 3,
     col: 16,
     pos: 23,
     stack: 'Error\n    at new JS_Parse_Error (eval at <anonymous> (/opt/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1545:18)\n    at js_error (eval at <anonymous> (/opt/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1553:11)\n    at croak (eval at <anonymous> (/opt/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2089:9)\n    at token_error (eval at <anonymous> (/opt/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2097:9)\n    at unexpected (eval at <anonymous> (/opt/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2103:9)\n    at semicolon (eval at <anonymous> (/opt/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2123:56)\n    at simple_statement (eval at <anonymous> (/opt/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2314:73)\n    at eval (eval at <anonymous> (/opt/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2164:47)\n    at eval (eval at <anonymous> (/opt/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2136:24)\n    at block_ (eval at <anonymous> (/opt/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2429:20)' } }
info:    Generating build/unbundled...
info:    Generating build/bundled...
warn:    Unable to optimize .js file /Users/splaktar/Git/gdgspacecoast/hoverboard/src/pages/blog-list.html_script_0.js 
{ err: 
   { message: 'SyntaxError: Unexpected token punc «(», expected punc «:»',
     filename: 0,
     line: 43,
     col: 28,
     pos: 967,
     stack: 'Error\n    at new JS_Parse_Error (eval at <anonymous> (/opt/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1545:18)\n    at js_error (eval at <anonymous> (/opt/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1553:11)\n    at croak (eval at <anonymous> (/opt/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2089:9)\n    at token_error (eval at <anonymous> (/opt/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2097:9)\n    at expect_token (eval at <anonymous> (/opt/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2110:9)\n    at expect (eval at <anonymous> (/opt/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2113:36)\n    at eval (eval at <anonymous> (/opt/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2686:13)\n    at eval (eval at <anonymous> (/opt/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2136:24)\n    at expr_atom (eval at <anonymous> (/opt/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2616:35)\n    at maybe_unary (eval at <anonymous> (/opt/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2792:19)' } }
info:    Build complete!
```

Browser view:
<img width="934" alt="screen shot 2016-08-07 at 5 07 57 pm" src="https://cloud.githubusercontent.com/assets/3506071/17465301/883f1748-5cc1-11e6-9744-e473ef4a9d0b.png">

In Firefox:
```
TypeError: /images/logo-white.svg is not a valid URL.
._computeImgDivARIALabel()
iron-image.html.js:216
._annotatedComputationEffect()
polymer.html.js:1622
Polymer.Bind._modelApi._effectEffects()
polymer.html.js:1429
Polymer.Bind._modelApi._propertySetter()
polymer.html.js:1413
Polymer.Bind._modelApi.__setProperty()
polymer.html.js:1422
._applyConfig()
polymer.html.js:2034
._afterClientsReady()
polymer.html.js:2028
```

Chrome Stable:
```
iron-image.html:342 Uncaught TypeError: Failed to construct 'URL': Invalid URL_computeImgDivARIALabel @ iron-image.html:342_annotatedComputationEffect @ polymer.html:1642_effectEffects @ polymer.html:1449_propertySetter @ polymer.html:1433__setProperty @ polymer.html:1442_applyConfig @ polymer.html:2054_afterClientsReady @ polymer.html:2048_ready @ polymer-mini.html:74_readyClients @ polymer-mini.html:82_ready @ polymer-mini.html:70_readyClients @ polymer-mini.html:82_ready @ polymer-mini.html:70_tryReady @ polymer-mini.html:60_initFeatures @ polymer.html:4053createdCallback @ polymer-micro.html:202window.Polymer @ polymer-micro.html:65(anonymous function) @ hoverboard-app.html:195(anonymous function) @ hoverboard-app.html:312
```

Chrome Canary:
```
iron-image.html:342 Uncaught TypeError: Failed to construct 'URL': Invalid URL(…)_computeImgDivARIALabel @ iron-image.html:342_annotatedComputationEffect @ polymer.html:1642_effectEffects @ polymer.html:1449_propertySetter @ polymer.html:1433__setProperty @ polymer.html:1442_applyConfig @ polymer.html:2054_afterClientsReady @ polymer.html:2048_ready @ polymer-mini.html:74_readyClients @ polymer-mini.html:82_ready @ polymer-mini.html:70_readyClients @ polymer-mini.html:82_ready @ polymer-mini.html:70_tryReady @ polymer-mini.html:60_initFeatures @ polymer.html:4053createdCallback @ polymer-micro.html:202window.Polymer @ polymer-micro.html:65(anonymous function) @ hoverboard-app.html:195(anonymous function) @ hoverboard-app.html:312
```

**Comment by rosterloh** [comment]
+1 I had the same thing. Had to remove the <iron-image tag to get the page to render

**Comment by ozasadnyy** [comment]
@Splaktar interesting. Which version of Polymer CLI are you using? I haven't updated to 0.13.0 yet and everything works fine.

**Comment by Splaktar** [comment]
It's hard to tell since `polymer --version` throws an exception and isn't a valid command. It's the latest version that is installed via the README instructions: `npm i -g polymer-cli`.

**Comment by Splaktar** [comment]
I re-ran the command and it says that the version is: `polymer-cli@0.13.0`

**Comment by ozasadnyy** [comment]
Try to install in this way
`npm i -g polymer-cli@0.12.0 `

**Comment by ozasadnyy** [comment]
[The issue with iron-image](https://github.com/PolymerElements/iron-image/issues/86) was fixed.
Still have problems with a new version of polymer-cli. Please use v.0.12.0 for now.

**Comment by Splaktar** [comment]
Thanks Oleh!

Fix can be found here: https://github.com/gdg-x/hoverboard/commit/d42df10eb82f4ab2867f31efd25363737bd74c27

**Comment by tasomaniac** [comment]
Should we close this issue as well? @Splaktar can you try to build the latest master?

**Comment by MrCsabaToth** [comment]
Had the same polymer build errors originally with 0.14, but enforcing 0.12 like it is now in the docs helped

**Comment by Splaktar** [comment]
Yep, docs include this information now. Thanks.
